config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy' 
  
  resources :products, :users

  root :to => 'products#index'
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :users do
    get 'new' => :new
    post 'create' => :create
    delete 'delete' => :destroy
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, :presence => true, :uniqueness => true
    validates :password, :confirmation => true
    attr_accessor :password_confirmation
    attr_reader :password
  
    validate :password_must_be_present
  
    # def User.encrypt_password(password, salt) 
    #     Digest::SHA2.hexdigest(password + salt)
    # end
  
    def password=(password) 
        @password = password
  
        if password.present?
            # generate_salt
            self.hashed_password = password
        end
    end
   
    def User.authenticate(name, password) 
        if user = find_by_name(name)
            if user.hashed_password == password
               user
            end
        end
    end
 
private
    def password_must_be_present 
        if hashed_password.present? == false
            errors.add(:password, "Missing password")
        end
    end
  
    # def generate_salt
    #     self.salt = self.object_id.to_s + rand.to_s
    # end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    set_user
  end

  # GET /products/1
  # GET /products/1.json
  def show
    set_user
  end

  # GET /products/new
  def new
    @product = Product.new
    set_user
  end

  # GET /products/1/edit
  def edit
    set_user
  end

  # POST /products
  # POST /products.json
  def create
    set_user
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    set_user
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    if session[:user_id] == nil
      @username =  ""
    else
      @username = session[:user_name]
    end
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end

    def set_user
      if session[:user_id] == nil
        @username =  ""
      else
        @username = session[:user_name]
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
      if (user = User.authenticate(params[:name], params[:password]))
            session[:user_id] = user.id
            session[:user_name] = user.name
            session[:user_admin] = user.isadmin
            if (user.isadmin == 0) 
                #admin
                redirect_to users_path
            else 
                #member
                redirect_to products_path
            end
      else
          redirect_to login_url, :alert => "Invalid username/password"
      end
  end

  def destroy
        session[:user_id] = nil
        session[:user_name] = nil
        session[:user_admin] = nil
        redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    check_session
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.find(params[:id])
    check_session
  end

  # GET /users/new
  def new
    @user = User.new
    @username = session[:user_name]
  end

  # GET /users/1/edit
  def edit
    check_session
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @username = session[:user_name]
    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :hashed_password, :salt, :password, :password_confirmation)
    end

    def check_session
      if session[:user_id] == nil || session[:user_id] == ''
        redirect_to login_url
      else
        @username = session[:user_name]
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
 
Time: <%= Time.now %> <br>
# There are <%= pluralize(@total_orders, "order") %>.
 
<%= button_to 'Logout', '/logout', :method => :delete %>

app/views/layouts/_footer.html.erb
<div id="footer-new">Clone by truongth
</div>
<script>
    var windowheight = window.innerHeight;
    var wrapperheight = document.getElementsByClassName('wrapper')[0].offsetHeight;
    var headerheight = document.getElementById('header-top').offsetHeight + document.getElementById('header-mid').offsetHeight
    var footerheight = document.getElementById('footer-new').offsetHeight
    if (wrapperheight < windowheight)
    {
		  document.getElementsByClassName('wrapper')[0].style.height = window.innerHeight - headerheight - footerheight + 'px';
    }
    function myFunction(event)
    {
      document.getElementById('product_image_url').value = document.getElementById('img_url').value;
      document.getElementById('product_image_url').value = document.getElementById('img_url').files.item(0).name;
      var files = event.target.files;
      var image = files[0];
      var reader = new FileReader();
      reader.onload = function(file) {
        var img = new Image();
        img.src = file.target.result;
        
        document.getElementById('content-img').src = img.src;
      }
      reader.readAsDataURL(image);
    }

</script>
<% if @username != nil && @username !='' %>
	<script type="text/javascript">
		document.getElementById('login-text').innerText = "Xin chào <%= @username %> \n Logout";
    console.log("A"+"<%= @username %>");
	</script>
<% end %>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Muachung: Khám phá những giá trị tiềm ẩn</title>
<link rel="shortcut icon" href="https://muachung.vn/favicon.ico?v=65.12" />
<%= stylesheet_link_tag 'general' %>
</head>
<body>
<div id="header-top"> 
	<div class="container"> 
		<div id="menu-left">
			<div id="icon-mc-area">
				<i id="icon-mc"></i>
			</div>
			<div id="icon-dl-area">
				<i id="icon-dl"></i>Du lịch
			</div>
		</div>
	</div>
</div>
<div id="header-mid">
	<div class="container"> 
		<div id="logo-area">
			<i id="logo"></i>
		</div>
		<div id="login-area">
			<i id="login"></i>
			<a style="">
				<%= link_to 'Đăng nhập / Đăng ký', sessions_destroy_path, id:"login-text" %>
			</a>
		</div>
	</div>
</div>
</body>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

app/views/products/_form.html.erb
<div id="product-content" class="container wrapper">
<%= form_with(model: product, local: true) do |form| %>
  <% if (product.image_url != nil
  ) %>
  <%= image_tag(product.image_url,class:"img-overlay", id:"content-img") %>
  <% else %>
  <%= image_tag("no-thumbnail.jpg" ,class:"img-overlay", id:"content-img") %>
  <% end %>
  <div id = "content-detail">
    <div class="product-field">
      <%= form.label :"Tên sản phẩm" %>
      <%= form.text_field :title %>
    </div>

    <div class="product-field">
      <%= form.label :"Mô tả sản phẩm" %>
      <%= form.text_area :description, :rows => 6, :cols => 80 %>
    </div>

    <div class="product-field">
      <%= form.label :"Giá sản phẩm" %>
      <%= form.text_field :price%>
    </div>
    
    <div class="product-field">
      <%= form.label :"Đường dẫn hình ảnh đại diện" %>
      <form action="/action_page.php">
        <input id="img_url" type="file" name="pic" accept="image/*" oninput="myFunction(event)">
      </form>
      <%= form.text_field :image_url %>
    </div>

    </br>
    <div class="link">
      <%= form.submit "Lưu thông tin sản phẩm" %>
      <%= link_to '<button type="button">Trở về trang chủ</button>'.html_safe, products_path %>
    </div>
  </div>
  
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product, class:"form-css" %>

app/views/products/index.html.erb
<div id="content" class="wrapper">
    <div id="content-top">
    <ul>
        <li class="tab selected">
            <%= link_to new_product_path, class:"img-thumb-deal product-upload tab-item" do %>
                Thêm sản phẩm mới
            <% end %>
        </li>
        <%if session[:user_admin] != nil && session[:user_admin] != ''%>
        <li class="tab selected">
                <%= link_to users_path, class:"img-thumb-deal product-upload tab-item" do %>
                    Quản lý người dùng
                <% end %>
        </li>
        <% end %>
    </ul>
    </div>
    <div id="content-main">
    <ul>
        <% @products.each do |product| %>
        <div class="tab-main" title=<%= product.title %>>
            <%# <div class="tab-main"> %>
                <div class="wrap-imgdesc">
                    <%= link_to edit_product_path(product), class:"img-thumb-deal" do %>
                        <% if (product.image_url != "") %>
                        <%= image_tag(product.image_url,class:"img-overlay") %>
                        <% else %>
                        <%= image_tag("no-thumbnail.jpg" ,class:"img-overlay") %>
                        <% end %>
                        <% end %>
                    <div class="discount-lbl">
                        <i class="icon iDiscount_mc"></i>
                        <span>-45<span class="unit-discount">%</span></span>
                    </div>
                </div>
                <div class="grp-bottom-content">
                    <div class="grp-name-price">
                        <h3 class="deal-name">
                            <%= link_to edit_product_path(product), class:"deal-name-val" do %>
                                <%= product.description %>
                            <% end %>
                        </h3>
                <div class="bottom-info">
                    <div class="deal-price">
                        <span class="sell-val"><%= product.price %><span class="unit">đ</span></span>
                        <span class="shop-p-val"><%= product.price*10 %><span class="unit">đ</span></span>
                    </div>
                    <div class="deal-buyer-counter clearfix">
                        <span class="make-left">Deal mới lên</span>
                    </div>
                    <%= link_to edit_product_path(product), class:"btn-go-detail" do %>
                        <i class="icon iDetail"></i>
                <% end %>
                </div>
            <%# </div> %>
        </div>
</div>
</div>
<% end %>
</ul>
</div>
</div>                                                                                      

app/views/products/new.html.erb
<h1>Thêm sản phẩm mới</h1>
<%= render 'form', product: @product%>

app/views/products/show.html.erb
<div class="wrapper">

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

</div>

app/views/users/_form.html.erb
<div class="wrapper container">
    <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>
                <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
  
        <fieldset class="user-field">
        <legend>Thông tin người dùng</legend>

        
        <table id="user-create">
            <tbody>
                <tr>
                    <td>
                        <%= f.label :name, 'UserName:' %> 
                    </td>
                    <td>
                        <%= f.text_field :name %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%= f.label :password, 'Password:' %>
                    </td>
                    <td>
                        <%= f.password_field :password %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <%= f.label :password_confirmation, 'Confirm:' %>
                    </td>
                    <td>
                        <%= f.password_field :password_confirmation %>
                    </td>
                </tr>
            </tbody>
        </table>

        </br>
        <div>
        <div class="button make-right">
            <%= f.submit "Tạo người dùng mới"%>
        </div> 
        <% if @username != nil && @username != '' %>
        <div class="button make-left">
            <%= link_to '<button type="button">Danh sách người dùng</button>'.html_safe, users_path %>
        </div>
        <%end%>
        </div>
        </fieldset>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="container">Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container wrapper" >
    <h1>Danh sách người dùng</h1>

    <div>
        <table id="user-table">
            <thead>
                <tr>
                    <th>UserName</th>
                    <th>Action</th>
                    <th>Role</th>
                </tr>
            </thead>

            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td>
                            <%= user.name %>
                        </td>
                        <td>
                            <%= link_to 'Hiển thị', user %>
                        </td>
                        <td>
                            <%if user.isadmin == 1%>
                                Admin
                                <%else%>
                                    Member
                                    <%end%>
                        </td>
                    </tr>
                    <% end %>
            </tbody>
        </table>

        <br>
        <div class="link">
        <span>
        <%= link_to '<button type="button">Trang chủ</button>'.html_safe, products_path %>
        <%= link_to '<button type="button">Tạo người dùng mới</button>'.html_safe, new_user_path %>
        <%= link_to '<button type="button">Đăng xuất</button>'.html_safe, login_url %>
        </span>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1 class="container">Thêm người dùng mới</h1>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="wrapper container">
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= @user.hashed_password %>
  </p>

  <p>
    <strong>Role:</strong>
    
    <%if @user.isadmin == 1%> Admin
    <% else %> Member
    <%end%>
  </p>

  <%= link_to 'Chỉnh sửa', edit_user_path(@user) %> |
  <%= link_to 'Quay lại', users_path %> 
</div>